comoequee-app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :crudtutoriais
  get 'tutorial/index'
  # Session and user routes
  get  '/login/',                     to: 'session#new',          as: 'login'
  post '/login/',                     to: 'session#create',       as: 'login-form'
  get  '/logout/',                    to: 'session#destroy',      as: 'logout'
  get  '/cadastro/',                  to: 'user#new',             as: 'register'
  post '/cadastro/',                  to: 'user#create',          as: 'register-form'
  get  '/delete/',                    to: 'user#destroy',         as: 'delete-user'
  # Login with google
  get  'auth/:provider/callback',     to: 'session#createGoogle', as: 'login-google'
  get  'auth/failure',                to: redirect('/login/'),    as: 'login-failure'
  # Tutorials
  get  '/tuto/:tutorial_id',          to: 'tutorial#show',        as: 'first-tutorial',   constraints: { tutorial_id: /.*/ }
  get  '/tutorial/:tutorial_id/:chapter_id/:content_id',          to: 'tutorial#index',       as: 'tutorial',         constraints: { tutorial_id: /.*/, chapter_id: /.*/, content_id: /.*/  }
  # Main routes
  get  '/perfil/',                    to: 'profile#index',        as: 'profile'
  get  '/tutoriais/',                 to: 'tutorials#index',      as: 'tutorials'
  get  '/index/',                     to: 'index#index',          as: 'index'

  root 'index#index'
  # FORMAT: get: [path], to: [controller#action], as: [name of route]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

end

comoequee-app/app/models/crudtutoriai.rb
class Crudtutoriai < ApplicationRecord
end

comoequee-app/app/controllers/crudtutoriais_controller.rb
class CrudtutoriaisController < ApplicationController
  before_action :set_crudtutoriai, only: [:show, :edit, :update, :destroy]

  # GET /crudtutoriais
  # GET /crudtutoriais.json
  def index
    @crudtutoriais = Crudtutoriai.all
  end

  # GET /crudtutoriais/1
  # GET /crudtutoriais/1.json
  def show
  end

  # GET /crudtutoriais/new
  def new
    @crudtutoriai = Crudtutoriai.new
  end

  # GET /crudtutoriais/1/edit
  def edit
  end

  # POST /crudtutoriais
  # POST /crudtutoriais.json
  def create
    @crudtutoriai = Crudtutoriai.new(crudtutoriai_params)

    respond_to do |format|
      if @crudtutoriai.save
        format.html { redirect_to @crudtutoriai, notice: 'Crudtutoriai was successfully created.' }
        format.json { render :show, status: :created, location: @crudtutoriai }
      else
        format.html { render :new }
        format.json { render json: @crudtutoriai.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crudtutoriais/1
  # PATCH/PUT /crudtutoriais/1.json
  def update
    respond_to do |format|
      if @crudtutoriai.update(crudtutoriai_params)
        format.html { redirect_to @crudtutoriai, notice: 'Crudtutoriai was successfully updated.' }
        format.json { render :show, status: :ok, location: @crudtutoriai }
      else
        format.html { render :edit }
        format.json { render json: @crudtutoriai.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crudtutoriais/1
  # DELETE /crudtutoriais/1.json
  def destroy
    @crudtutoriai.destroy
    respond_to do |format|
      format.html { redirect_to crudtutoriais_url, notice: 'Crudtutoriai was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crudtutoriai
      @crudtutoriai = Crudtutoriai.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crudtutoriai_params
      params.require(:crudtutoriai).permit(:id_seq, :namecourse, :namechapter, :contentchapter, :duration)
    end
end

comoequee-app/app/helpers/crudtutoriais_helper.rb
module CrudtutoriaisHelper
end

comoequee-app/app/views/crudtutoriais/_form.html.erb
<%= form_with(model: crudtutoriai, local: true) do |form| %>
  <% if crudtutoriai.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crudtutoriai.errors.count, "error") %> prohibited this crudtutoriai from being saved:</h2>

      <ul>
      <% crudtutoriai.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_seq %>
    <%= form.text_field :id_seq %>
  </div>

  <div class="field">
    <%= form.label :namecourse %>
    <%= form.text_field :namecourse %>
  </div>

  <div class="field">
    <%= form.label :namechapter %>
    <%= form.text_field :namechapter %>
  </div>

  <div class="field">
    <%= form.label :contentchapter %>
    <%= form.text_field :contentchapter %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

comoequee-app/app/views/crudtutoriais/edit.html.erb
<h1>Editing Crudtutoriai</h1>

<%= render 'form', crudtutoriai: @crudtutoriai %>

<%= link_to 'Show', @crudtutoriai %> |
<%= link_to 'Back', crudtutoriais_path %>

comoequee-app/app/views/crudtutoriais/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crudtutoriais</h1>

<table>
  <thead>
    <tr>
      <th>Id seq</th>
      <th>Namecourse</th>
      <th>Namechapter</th>
      <th>Contentchapter</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crudtutoriais.each do |crudtutoriai| %>
      <tr>
        <td><%= crudtutoriai.id_seq %></td>
        <td><%= crudtutoriai.namecourse %></td>
        <td><%= crudtutoriai.namechapter %></td>
        <td><%= crudtutoriai.contentchapter %></td>
        <td><%= crudtutoriai.duration %></td>
        <td><%= link_to 'Show', crudtutoriai %></td>
        <td><%= link_to 'Edit', edit_crudtutoriai_path(crudtutoriai) %></td>
        <td><%= link_to 'Destroy', crudtutoriai, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crudtutoriai', new_crudtutoriai_path %>

comoequee-app/app/views/crudtutoriais/new.html.erb
<h1>New Crudtutoriai</h1>

<%= render 'form', crudtutoriai: @crudtutoriai %>

<%= link_to 'Back', crudtutoriais_path %>

comoequee-app/app/views/crudtutoriais/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id seq:</strong>
  <%= @crudtutoriai.id_seq %>
</p>

<p>
  <strong>Namecourse:</strong>
  <%= @crudtutoriai.namecourse %>
</p>

<p>
  <strong>Namechapter:</strong>
  <%= @crudtutoriai.namechapter %>
</p>

<p>
  <strong>Contentchapter:</strong>
  <%= @crudtutoriai.contentchapter %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @crudtutoriai.duration %>
</p>

<%= link_to 'Edit', edit_crudtutoriai_path(@crudtutoriai) %> |
<%= link_to 'Back', crudtutoriais_path %>